.github/workflows/gradle.yml
app/build.gradle
app/src/main/java/dev/jeremylong/nvd/cli/Application.java
app/src/main/java/dev/jeremylong/nvd/cli/commands/AbstractHelpfulCommand.java
app/src/main/java/dev/jeremylong/nvd/cli/commands/AbstractNvdCommand.java
app/src/main/java/dev/jeremylong/nvd/cli/commands/CveCommand.java
app/src/main/java/dev/jeremylong/nvd/cli/commands/SetupCommand.java
app/src/main/java/dev/jeremylong/nvd/cli/model/CveOutput.java
buildSrc/build.gradle
buildSrc/src/main/config/java.license
buildSrc/src/main/config/spotbugs.exclude.xml
buildSrc/src/main/config/spotless.eclipseformat.xml
buildSrc/src/main/groovy/nvd.tools.java-common-conventions.gradle
nvd-lib/src/main/java/dev/jeremylong/nvdlib/NvdApiException.java
nvd-lib/src/main/java/dev/jeremylong/nvdlib/NvdCveApi.java
nvd-lib/src/main/java/dev/jeremylong/nvdlib/NvdCveApiBuilder.java
nvd-lib/src/main/java/dev/jeremylong/nvdlib/RateLimitedClient.java
nvd-lib/src/main/java/dev/jeremylong/nvdlib/RateMeter.java
nvd-lib/src/test/java/dev/jeremylong/nvdlib/NvdCveApiTest.java
nvd-lib/src/test/java/dev/jeremylong/nvdlib/RateMeterTest.java
settings.gradle

- add plugins: `spotless` and `spotbugs`
- automatically format code with `spotlessApply`
- fix bugs identified by `spotbugs`

quality: add spotbugs and spotless

---

app/src/main/java/io/github/jeremylong/nvd/cli/commands/CveCommand.java
app/src/main/java/io/github/jeremylong/nvd/cli/model/CveOutput.java
app/src/main/resources/nvd
nvd-lib/src/main/java/io/github/jeremylong/nvdlib/NvdCveApi.java
nvd-lib/src/main/java/io/github/jeremylong/nvdlib/RateLimitedClient.java
nvd-lib/src/main/java/io/github/jeremylong/nvdlib/RateMeter.java
nvd-lib/src/test/java/io/github/jeremylong/nvdlib/RateMeterTest.java

- bug fixes
- update how the rate meter works; it now uses an auto-closable ticket so the ticket gets replaced in the queue with the time the operation ended.

Bug Fix & Updates

---

app/src/main/java/io/github/jeremylong/nvd/cli/commands/AbstractNvdCommand.java
app/src/main/java/io/github/jeremylong/nvd/cli/commands/CveCommand.java
nvd-lib/src/main/java/io/github/jeremylong/nvdlib/NvdCveApi.java
nvd-lib/src/main/java/io/github/jeremylong/nvdlib/NvdCveApiBuilder.java
nvd-lib/src/main/java/io/github/jeremylong/nvdlib/RateLimitedClient.java
nvd-lib/src/main/java/io/github/jeremylong/nvdlib/RateMeter.java

Adds multi-threading capabilities. Using 4 threads and an API key downloading the entire NVD Vulnerability data-set took ~90 seconds.

feat: add multi-threading

---

README.md

Trivial things like this can still trip people up ;)

Fix docs for installing vulnz

---

nvd-lib/src/main/java/io/github/jeremylong/nvdlib/NvdApiException.java
nvd-lib/src/main/java/io/github/jeremylong/nvdlib/NvdCveApi.java
nvd-lib/src/main/java/io/github/jeremylong/nvdlib/NvdCveApiBuilder.java
nvd-lib/src/main/java/io/github/jeremylong/nvdlib/RateLimitedClient.java
nvd-lib/src/main/java/io/github/jeremylong/nvdlib/RateMeter.java
nvd-lib/src/test/java/io/github/jeremylong/nvdlib/NvdCveApiTest.java
nvd-lib/src/test/java/io/github/jeremylong/nvdlib/RateMeterTest.java
nvd-lib/src/test/java/io/github/jeremylong/nvdlib/nvd/CveApiJson20Test.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/Application.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/AbstractHelpfulCommand.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/AbstractNvdCommand.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/CveCommand.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/InstallCommand.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/MainCommand.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/TimedCommand.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/model/CveOutput.java
vulnz/src/test/java/io/github/jeremylong/vulnz/cli/NvdApplicationTests.java

apparently gradle automatically updates this on build

Update copyright year

---

nvd-lib/src/main/java/io/github/jeremylong/nvdlib/NvdCveApi.java

fix: use bodyAsBytes if bodyAsText is null

---

nvd-lib/src/main/java/io/github/jeremylong/nvdlib/NvdCveApiBuilder.java

feat(nvd-lib): support noRejected

---

nvd-lib/build.gradle

- do not include generated sources in sources.

chore(nvd-lib): correct build sourceSets

---

nvd-lib/src/main/java/io/github/jeremylong/nvdlib/NvdCveApiBuilder.java

feat(nvd-lib): add virtual match string parameter

---

nvd-lib/src/main/java/io/github/jeremylong/nvdlib/NvdCveApiBuilder.java

feat(nvd-lib): add version start and version end

---

CHANGELOG.md
buildSrc/src/main/groovy/vuln.tools.java-common-conventions.gradle
gh-advisory-lib/README.md
nvd-lib/README.md
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/GHSACommand.java

Removed unused code that was causing an exception

fix: invalid value for year when calling `ghsa`

---

data-source/build.gradle
gh-advisory-lib/build.gradle
nvd-lib/build.gradle

Shot in the dark for #42, but did not have any effect.

Update httpclient from 5.1.3 to 5.2

---

buildSrc/src/main/groovy/vuln.tools.java-common-conventions.gradle
open-vulnerability-clients/README.md
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/ghsa/GitHubSecurityAdvisoryClient.java
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/RateLimitedClient.java
vulnz/build.gradle

- ensure spring-boot does not downgrade httpclient5
- remove unnecessary code

build(deps): bump httpclient5

---

open-vulnerability-store/src/main/java/io/github/jeremylong/openvulnerability/VulnerabilityTransformer.java
open-vulnerability-store/src/main/java/io/github/jeremylong/openvulnerability/model/Source.java

populate with sourceIdentifier for NVD, fixes #55

feat: database: add 'meta' column to 'source'

---

open-vulnerability-store/build.gradle

Update hibernate from 6.1.7 to 6.2.7

---

vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/CveCommand.java

- improves error handling so that a failed request to the NVD does not corrupt the local cache
- resolves #64

fix: improve error handling

---

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClient.java

fix: correct retry for non-json response

---

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/Config.java
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CpeMatch.java
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CveItem.java
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CvssV2.java
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CvssV3.java
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CvssV3Data.java
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/DefCveItem.java
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/LangString.java
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/Metrics.java
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/Node.java
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/Reference.java
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/VendorComment.java
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/Weakness.java

- add missing constructors
- improve toString on CvssV2 and CvssV3
- improve parsing of Cvss vector strings

feat: add constructors and other minor improvements

---

vulnz/README.md

docs: improve documentation

---

vulnz/README.md

Update doc to include 403 Forbidden responses.

docs: Update README.md

---

buildSrc/src/main/groovy/vuln.tools.java-common-conventions.gradle
open-vulnerability-clients/README.md
open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClient.java
vulnz/README.md

fix: prevent NPE

---

buildSrc/src/main/groovy/vuln.tools.java-application-conventions.gradle
buildSrc/src/main/groovy/vuln.tools.java-common-conventions.gradle
gradle/wrapper/gradle-wrapper.properties
open-vulnerability-clients/README.md
vulnz/README.md
vulnz/build.gradle
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/CveCommand.java

- bump gradle wrapper version
- fix vulnz publication in `build.gradle`
- temporarily remove `spotbugs` as it is incompatible with gradle 8.6
- fix unchecked error in compilation
- updated documentation for 6.0.0

chore: prepare release 6.0.0

---

vulnz/README.md

docs: remove zip step from "Creating the Cache" in README.md

do not zip cache content as it already comes zipped

---

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CveItem.java
open-vulnerability-clients/src/main/resources/json/cve_api_json_2.0.schema

resolves #154
We likely won't publish a new version as there are no impactful changes to the project.

docs: update schema

---

vulnz/src/main/resources/application.properties

spring.main.log-startup-info set false

Update application.properties log startup info set false

---

open-vulnerability-clients/src/main/resources/json/cve_api_json_2.0.schema
open-vulnerability-clients/src/main/resources/json/cvss-v4.0.json

To help get the ball rolling for #163, updated the schema to 2.2 and added the CVSS v4.0 schema. Happy to collaborate with others or throw this away :-)

feat: update schema version for CVSSv4

---

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClient.java

Use force getBodyBytes

---

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClientBuilder.java

docs: ensure JavaDoc is explicit about UTC

---

vulnz/README.md

docs: correct docker image version number

---

.github/workflows/vulnz-docker-release.yml

chore: add support for docker linux/arm64

---

vulnz/Dockerfile

updated per https://github.com/jeremylong/Open-Vulnerability-Project/issues/203\#issuecomment-2260282565

fix: adjust java memory usage

---

vulnz/README.md

One of the commands used an invalid image tag.

Fix image tag

---

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdApiRetryStrategy.java

fix: log ordinal values instead of integers

---

vulnz/Dockerfile

Reverts jeremylong/Open-Vulnerability-Project#224

fix: JAVA_OPT

---

vulnz/Dockerfile

fix: dont cap the memory in the docker image

---

vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/CveCommand.java

Fixing #267 missing the CVEs of the 1. Jan of every year

Fix missing CVEs from first day of the year fixes #267

---

vulnz/Dockerfile
vulnz/src/docker/apache/htdocs/epss.shtml
vulnz/src/docker/apache/htdocs/index.html
vulnz/src/docker/apache/htdocs/kev.shtml
vulnz/src/docker/apache/htdocs/nvd.shtml
vulnz/src/docker/apache/mirror.conf
vulnz/src/docker/crontab/mirror
vulnz/src/docker/scripts/epss.sh
vulnz/src/docker/scripts/kev.sh
vulnz/src/docker/scripts/mirror-all.sh
vulnz/src/docker/scripts/mirror.sh
vulnz/src/docker/scripts/validate.sh
vulnz/src/docker/supervisor/supervisord.conf

- mirror EPSS and KEV
- add `index.html` to make the mirror a little prettier
- Uses server side includes to provide a directory listing of EPSS, KEV, and the NVD mirrors

feat: mirror additional sources

---

vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/InstallCommand.java

Paths changed with the spring-boot upgrade. This corrects the install command.
resolves #295

fix: update install command

---

vulnz/src/docker/scripts/epss.sh
vulnz/src/docker/scripts/kev.sh

fix: follow redirects when retrieving EPSS and KEV

---

vulnz/src/main/java/io/github/jeremylong/vulnz/cli/Application.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/cache/CacheException.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/cache/CacheProperties.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/cache/CacheUpdateException.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/AbstractHelpfulCommand.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/AbstractJsonCommand.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/AbstractNvdCommand.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/CveCommand.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/GHSACommand.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/InstallCommand.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/MainCommand.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/TimedCommand.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/model/BasicOutput.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/monitoring/CveCounterPerYear.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/monitoring/PrometheusFileWriter.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/services/NvdMirrorService.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/services/NvdService.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/ui/IProgressMonitor.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/ui/JLineAppender.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/ui/JlineShutdownHook.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/ui/ProgressMonitor.java
vulnz/src/main/java/io/github/jeremylong/vulnz/cli/util/HexUtil.java

Adds fairly pointless, generated javadoc to fix build warnings.

chore(javadoc): fix build warnings regarding missing javadoc

---

vulnz/src/docker/scripts/mirror.sh

fix: remove unused arg from mirror.sh

---

build.gradle.kts

As the vulnz CLI is a Spring Boot executable JAR, we can no longer publish this to central.

build: remove central publishing
