jeremylong/open-vulnerability-cli

CHANGELOG.md, buildSrc/src/main/groovy/vuln.tools.java-common-conventions.gradle, gh-advisory-lib/README.md, gh-advisory-lib/src/main/java/io/github/jeremylong/ghsa/CWE.java, gh-advisory-lib/src/main/java/io/github/jeremylong/ghsa/CWEs.java, gh-advisory-lib/src/main/java/io/github/jeremylong/ghsa/GitHubSecurityAdvisoryClient.java, gh-advisory-lib/src/main/java/io/github/jeremylong/ghsa/Identifier.java, gh-advisory-lib/src/main/java/io/github/jeremylong/ghsa/Package.java, gh-advisory-lib/src/main/java/io/github/jeremylong/ghsa/SecurityAdvisories.java, gh-advisory-lib/src/main/java/io/github/jeremylong/ghsa/SecurityAdvisory.java, gh-advisory-lib/src/main/java/io/github/jeremylong/ghsa/SecurityAdvisoryResponse.java, gh-advisory-lib/src/main/java/io/github/jeremylong/ghsa/Vulnerabilities.java, gh-advisory-lib/src/main/java/io/github/jeremylong/ghsa/Vulnerability.java, gh-advisory-lib/src/test/java/io/github/jeremylong/ghsa/SerializationTest.java, nvd-lib/README.md
- ensure we can serialize and deserialize the ghsa model
- correct type names and visibility
- fix possible NPE
I'm still not happy with having the `edge` nodes in the serialization - but it is the only way I can figure out how to have a single model that can deserialize the response from GitHub's GraphQL endpoint and serialize/deserialize a slightly condensed schema.
=> fix: ensure we can serialize/deserialize the ghsa model

gh-advisory-lib/src/main/java/io/github/jeremylong/ghsa/GitHubSecurityAdvisoryClientBuilder.java
Custom endpoints set via `GitHubSecurityAdvisoryClientBuilder#withEndpoint` when building the GitHub client did not take effect, as they were not passed to the client instance when calling `build()` on the builder.
=> Pass custom `endpoint` to `GitHubSecurityAdvisoryClient` when set

open-vulnerability-clients/build.gradle, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/ghsa/GitHubSecurityAdvisoryClient.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/ghsa/GitHubSecurityAdvisoryClientBuilder.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/ghsa/SecurityAdvisory.java, open-vulnerability-clients/src/main/resources/securityAdvisories.mustache, open-vulnerability-clients/src/test/java/io/github/jeremylong/openvulnerability/client/ghsa/GitHubSecurityAdvisoryClientTest.java, open-vulnerability-clients/src/test/java/io/github/jeremylong/openvulnerability/client/ghsa/SerializationTest.java, open-vulnerability-clients/src/test/resources/advisories.json, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/GHSACommand.java
Add SecurityAdvisory `classification` for GitHub Advisory.
https://docs.github.com/en/graphql/reference/objects#securityadvisory
```bash
$ ./vulnz/build/libs/vulnz-4.0.1.jar ghsa --updatedSince="2023-05-01T00:00:00Z" > result.json
$ ./vulnz/build/libs/vulnz-4.0.1.jar ghsa --updatedSince="2023-05-01T00:00:00Z" --classifications="GENERAL" > result1.json
$ ./vulnz/build/libs/vulnz-4.0.1.jar ghsa --updatedSince="2023-05-01T00:00:00Z" --classifications="MALWARE" > result.json
```
[result.json.txt](https://github.com/jeremylong/Open-Vulnerability-Project/files/11396701/result.json.txt)
[result2.json.txt](https://github.com/jeremylong/Open-Vulnerability-Project/files/11396703/result2.json.txt)
=> Add SecurityAdvisory classification for GitHub Advisory

buildSrc/src/main/groovy/vuln.tools.java-common-conventions.gradle, open-vulnerability-clients/README.md, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdApiRetryStrategy.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClient.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClientBuilder.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/RateLimitedClient.java, vulnz/README.md, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/AbstractNvdCommand.java, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/CveCommand.java
With this update I was able to create a local cache of the NVD in ~30 minutes. Prior to releasing ODC 9.0.0 this took ~2 minutes - so the number of users from the ODC community appear to be crushing the NVD API atm.
=> fix: add retry on 503 errors

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdApiRetryStrategy.java
Failed requests with 502 and 504 should also be retried as they usually also indicate short term failures.
=> fix: retry 502 and 504

buildSrc/src/main/groovy/vuln.tools.java-common-conventions.gradle, open-vulnerability-clients/README.md, vulnz/README.md, vulnz/build.gradle, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/CveCommand.java
I've had a few offline requests to add the 'meta' files to the cache of the NVD data. This PR appears to correctly generate the (of course without the `zip` entries).
=> feat: produce NVD meta data for cache

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/epss/EpssDataFeed.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/ghsa/GitHubSecurityAdvisoryClient.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/kev/KevDataFeed.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/RateLimitedClient.java
=> fix: resolve proxy auth issue

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/HttpAsyncClientSupplier.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/HttpClientSupplier.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/epss/EpssDataFeed.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/ghsa/GitHubSecurityAdvisoryClient.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/ghsa/GitHubSecurityAdvisoryClientBuilder.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/kev/KevDataFeed.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClient.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClientBuilder.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/RateLimitedClient.java
The ability to customize clients makes it easier to integrate this library into applications more smoothly. Applications may wish to set custom `User-Agent` headers, configure proxies through ways other than Java system properties, hook in metrics collection, and more.
=> feat: allow for custom http clients to be provided

vulnz/src/docker/scripts/mirror.sh
This primarily fix situation where DELAY override is incorrect.
Previous behaviors:
* If DELAY is unset, will set DELAY_ARG to "--delay=" (empty string after equal sign) 
* If DELAY is set, DELAY_ARG will be set to "--delay=10000" if NVD_API_KEY unspecified. DELAY value will never be used.
Changed Behavior
* If DELAY is unset, 
* if NVD_API_KEY unspecified, DELAY_ARG will be set to "--delay=10000"
* if NVD_API_KEY specified, DELAY_ARG will be empty string (I assume will default to value in CLI)
* If DELAY is set , for example to "1234", DELAY_ARG will be set to "--delay=1234"
=> Update mirror.sh to fix DELAY Override

vulnz/README.md
Fix typo in identifier: 'vunlz' to 'vulnz'
=> Fix typo in identifier: 'vunlz' to 'vulnz'

vulnz/Dockerfile
This commit grants the necessary permissions to the 'mirror' user to resolve a Docker start failure issue, specifically an access error (EAccess). It was found that this error was due to insufficient permissions for the 'mirror' user. By providing the appropriate permissions, Docker can now start without issues, thereby eliminating the error that was hindering its proper operation.
=> Add permissions to mirror user to fix Docker start failure (EAccess)

vulnz/Dockerfile
Adding the tzdata package allows setting the timezone via environment variable TZ, e.g. `TZ=Europe/Berlin`
=> feat: added tzdata package for timezone support

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CveItem.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClient.java
This is a fast fix for the [vulnz is failing cve caching from NVD due to an introduced 'cveTags' property](https://github.com/jeremylong/Open-Vulnerability-Project/issues/150) issue.
It simply ignores unkown properties on the CveItem.java and logs an error if the json parsing fails.
=> Ignore unkown properties on CveItem to support new 'cveTags' property

vulnz/build.gradle
Fixes some of the CVEs in transitive dependencies. I do not believe any of the CVEs affect the `vulnz` CLI; but we are upgrading anyway.
=> build(deps): bump versions

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/RateLimitedClient.java
Adding a call to shutdown() to avoid the consequences of Executor error
=> fix: Adding a call to shutdown()

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdApiRetryStrategy.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/RateLimitedClient.java
=> fix: additional logging

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClient.java, open-vulnerability-clients/src/test/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClientIntegrationTest.java
Fixes #167 
For purposes of discussion/demonstration, changes the error handling for the NVD API to specifically fail if the JSON cannot be parsed, as this is likely a fatal error that needs resolving, so retrying and getting stuck is probably not helpful, and creates additional NVD API load.
There are not really good/strong automated tests here, but this adjusts the existing integration test to
- propagate system env API key to the client
- make some basic assertions (should be at least one updated CVE in the last 120 days...)
- fail test if there is an exception
- timeout after 2 minutes
Failed test will yield
```
> Task :open-vulnerability-clients:test
NvdCveClientIntegrationTest > update() FAILED
io.github.jeremylong.openvulnerability.client.nvd.NvdApiException at …
```
=> fix: Fail fast on NVD API JSON object mapping/binding errors

gradle.properties, open-vulnerability-clients/README.md, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/epss/EpssItem.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/kev/KevCatalog.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/kev/KevItem.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/Config.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CpeMatch.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CvssV2Data.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CvssV3Data.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/Metrics.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/Node.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/Reference.java, vulnz/README.md
As noted in https://github.com/jeremylong/DependencyCheck/issues/6747 NVD have added `cvssMetricV40` to their API which breaks this library as it is using strict deserialisation in many places it shouldnt.
This change helps workaround/fix https://github.com/jeremylong/DependencyCheck/issues/6747 and https://github.com/jeremylong/DependencyCheck/issues/6746 in the short term, before #163 is implemented.
=> fix: workaround lack of CVSSv4 support with consistently lenient JSON parsing

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CvssV4Data.java
Follow-up to #170 
The schema does not prohibit additional properties being added:
https://github.com/jeremylong/Open-Vulnerability-Project/blob/83189a18225029b1cb535f747e6b7662acfd0ecd/open-vulnerability-clients/src/main/resources/json/cvss-v4.0.json
This will be more robust if NVD add yet new crazy things, or rename the misnamed properties back where they should be....
=> fix: allow lenient parsing of CvssV4Data

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CveItem.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CveTag.java
- https://github.com/jeremylong/Open-Vulnerability-Project/pull/151
Disputed information is now only included in cveTags.
Fixed to include cveTags
=> Add cveTags property

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClient.java
Cap recursive calls to `next()` under failure conditions.
=> fix: prevent memory leak 

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClient.java, open-vulnerability-clients/src/test/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClientTest.java
resolves https://github.com/jeremylong/DependencyCheck/issues/6834
=> fix: respect NVD error message for resultsPerPage

vulnz/Dockerfile, vulnz/src/docker/crontab/mirror, vulnz/src/docker/scripts/mirror.sh
This will help analyzing cron issues since docker stdout is also flooded by access logs and the last cron task output is hardly every visible
=> Ensure we log cron tasks locally

vulnz/src/docker/scripts/mirror.sh
Fixed a typo, so now the max retry attempts gets logged correctly in the docker script.
=> fix: Correctly log MAX_RETRY

vulnz/src/docker/scripts/mirror.sh
Refactor the cache validation process to check each gzip file individually. If a corrupt file is detected, the script now provides the specific filename before clearing the cache and rerunning the mirror process. This change enhances error reporting.
Spelling error: Valdiating -> Validating
=> #230 & #232 Improve cache validation logic in mirror.sh script

.gitattributes, vulnz/README.md, vulnz/build.gradle, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/Application.java, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/CveCommand.java, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/monitoring/PrometheusFileWriter.java, vulnz/src/main/resources/application.properties, vulnz/src/main/resources/banner.txt
1.) To better monitor the vulzn CLI, a scheduler has been implemented that writes metrics to the htdocs folder. These metrics can be read by a Prometheus system, for example. Metrics are only written if the vulzn CLI is also running. This feature is disabled by default and can be enabled via the ENV variable `METRICS_ENABLE=true`. This is used for better analysis of memory issues. The metrics can be accessed via HTTP at /metrics. This additional metrics file does not affect the OWASP dependency check. To achieve this, new dependencies had to be added to the project. Currently, only the standard JVM metrics are being written, but it can also be extended to include custom metrics.
2.) As an additional improvement to track version changes based on the log, the banner was extended to include …
=> Monitoring for the vulnz cli (#230)

vulnz/src/docker/scripts/mirror.sh
=> feat: validate gz files

vulnz/README.md, vulnz/build.gradle, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/Application.java, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/CveCommand.java, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/monitoring/PrometheusFileWriter.java, vulnz/src/main/resources/application.properties
Bugfix: Remove _TaskSchedulingAutoConfiguration.class_ from the exclude list to ensure that the scheduler for writing metrics is also started.
Introduce a new property: `metrics.write.interval.` This allows you to configure the invocation interval for writing metrics.
Update the documentation accordingly:
New metrics added:
````
application_total{name="nvd",version="7.1.0"} 1.0
application_created{name="nvd",version="7.1.0"} 1734819109.346
cve_counter 243324.0
cve_load_counter 1.0
````
=> Monitoring bug fixes and enhancements

vulnz/Dockerfile, vulnz/src/docker/crontab/validate, vulnz/src/docker/scripts/mirror.sh, vulnz/src/docker/scripts/validate.sh
Fixes #244 
- use exec to replace the bash script, not fork a different process
- use dedicated validate process
=> Fix kill signal handling #244

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/ghsa/CVSSSeverities.java, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/ghsa/SecurityAdvisory.java, open-vulnerability-clients/src/main/resources/securityAdvisories.mustache
Add SecurityAdvisory `cvssSeverities` and deprecate `cvss`
https://docs.github.com/en/graphql/reference/objects#securityadvisory
> cvss is deprecated.
> cvss will be removed. New cvss_severities field will now contain both cvss_v3 and cvss_v4 properties. Removal on 2025-10-01 UTC.
CVSS v4 only exists in `cvss_severities`. The `cvss` field is deprecated as it will be removed on 2025-10-01 UTC.
https://docs.github.com/en/graphql/overview/breaking-changes#changes-scheduled-for-2025-10-01
```bash
java -jar vulnz/build/libs/vulnz-7.1.0.jar ghsa --updatedSince="2025-01-10T00:00:00Z" > result.json
```
[result.json.txt](https://github.com/user-attachments/files/18410944/result.json.txt)
=> Add SecurityAdvisory cvssSeverities and deprecate cvss

vulnz/README.md, vulnz/build.gradle, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/monitoring/PrometheusFileWriter.java, vulnz/src/main/resources/application.properties
Change from io.prometheus:client_java to io.prometheus:prometheus-metrics-core to fix #255
Introduced a new `METRICS_WRITE_FORMAT` property to allow switching between OpenMetrics and Prometheus formats for metric exposition. Updated relevant logic, dependencies, and documentation to support this functionality. Default remains `openmetrics`.
Prometheus versions older than 3 lack support for the OpenMetrics format.
=> Add support for configurable metrics output format and fixes #255

gradle.properties, vulnz/build.gradle, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/CveCommand.java
Improves memory usage when updating the NVD data cache.
@EugenMayer can you take a look at this one? I haven't run it through a profiler yet, but it should be much better on updates unless the NVD does a mass update again.
=> fix: improve memory usage

.gitignore, open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/NvdCveClientBuilder.java, vulnz/Dockerfile, vulnz/README.md, vulnz/src/docker/crontab/mirror, vulnz/src/docker/crontab/validate, vulnz/src/docker/scripts/mirror.sh, vulnz/src/docker/supervisor/supervisord.conf, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/CveCommand.java, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/model/CvesNvdPojo.java
Reimplement NVD caching to reduce the memory footprint and improve performance - fixes #258
This PR reduces the memory load by a magnitude, in terms, we hold as maximum of 'all entries of a year' in the memory. The current process holds 'all entries of all year' and thus it will use more and more memory each year passing.
The current max-memory usage with the new implementation is about `560MB`, while the old implementation did not finish with a limit of `7GB`
If someone wants to test it, use the docker image
```bash
export APIKEY=123
docker run --name vulnz -e NVD_API_KEY=$APIKEY -e DELAY=100 ghcr.io/eugenmayer/vulnz:v7.3.0-9
```
=> Reimplement caching to use a per-year scope fixes #258

open-vulnerability-clients/src/main/java/io/github/jeremylong/openvulnerability/client/nvd/CvssV4Data.java, open-vulnerability-clients/src/test/java/io/github/jeremylong/openvulnerability/client/nvd/SerializationTest.java
Incorrectly used the wrong type for three fields that are rarely filled out in the NVD data. This resolves https://github.com/jeremylong/Open-Vulnerability-Project/issues/270
@marcelstoer thanks for suggesting adding the test case via #272 - I've included that here.
=> fix: use correct types for modifiedSubAvailabilityImpact, modifiedSubIntegrityImpact, and modifiedSubConfidentialityImpact

vulnz/build.gradle, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/cache/CacheProperties.java, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/cache/CacheUpdateException.java, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/CveCommand.java, vulnz/src/main/resources/logback-spring.xml
If performing a full download of the NVD data for purposes of creating a local mirror - enable forced, persistent HTTP Caching of the responses from the NVD API.
1. Only enable caching when creating a full mirror.
2. Delete any existing HTTP cached files if the full update is successful.
3. Set a status code of 100 so we can watch for this and kick off the download again.
This is a draft PR as it is pending the release of https://github.com/jeremylong/open-vulnerability-clients/pull/4.
=> feat: implement forced http caching on full mirror of NVD

vulnz/src/main/java/io/github/jeremylong/vulnz/cli/services/NvdMirrorService.java
Fixes issue #293 by warning the user that they likely used the wrong command-line syntax for the `--directory` option (unless they truly wished to cache underneath a `~`-folder.
```
aikebah@rajah open-vulnerability-cli % java -jar vulnz/build/libs/vulnz-8.0.1-local.jar cve --directory=~/.vulnz-mirror --cache --threads=4
_/
_/      _/   _/    _/    _/     _/_/_/     _/_/_/_/
_/      _/   _/    _/    _/     _/    _/       _/
_/  _/     _/    _/    _/     _/    _/     _/
_/         _/_/_/    _/     _/    _/   _/_/_/_/
Version: 8.0.1-local
Open Vulnerability Project
💖 Sponsor: https://github.com/sponsors/jeremylong
NVD_API_KEY not found. Supply an API key for more generous rate limits
Cache directory is starting with '~', did you intend to target a user home directory? Then separate the …
```
=> fix: Issue a warning when users have used an un-resolved user-home relative path

README.md, vulnz/src/docker/scripts/epss.sh, vulnz/src/docker/scripts/kev.sh
Introduce the `CACERT` option for specifying a custom CA certificate file to enhance secure SSL/TLS connections in `kev.sh` and `epss.sh` scripts. Updated `README.md` to document the usage and provide Docker run examples leveraging custom certificates.
=> Fix the problem #309 Add support for custom CA certificates in scripts

README.md, gradle.properties, vulnz/build.gradle, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/AbstractNvdCommand.java, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/CveCommand.java
BREAKING CHANGE:
- feat: The new argument for CveCommand `--requestCount` is the number of requests allowed over a 30-second rolling window. The `--threads` argument was removed.
- build(deps): bump `io.github.jeremylong:open-vulnerability-clients` from 7.3.2 to 8.0.0
-  See release notes: https://github.com/jeremylong/open-vulnerability-clients/releases/tag/v8.0.0
=> feat!: CveCommand replaces --threads argument with --requestCount

README.md, gradle.properties, vulnz/build.gradle, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/AbstractNvdCommand.java, vulnz/src/main/java/io/github/jeremylong/vulnz/cli/commands/CveCommand.java
BREAKING CHANGE:
- bump open-vulnerbility-clients from 7.3.2 to 8.0.0.
- remove `--threads` argument from the CVE Command as the client library no longer accepts the parameter.
- add `--requestCount` to CVE Command to specify the number of requests allowed over a rolling 30-second window.
=> feat!: CveCommand replaces --threads argument with --requestCount 
